API_KEY = "65a13c871b9992dc2e2d78ccbfd5bbe4"
data_sitekey = '6LdaB7UUAAAAAD2w3lLYRQJqsoup5BsYXI2ZIpFF'
page_url ='https://all-access.wax.io/'
game_url = 'https://play.alienworlds.io/'
alcor = "https://wax.alcor.exchange/"
user_name = 'chrlschwb@gmail.com'
pass_word = 'igh39d#di'
tesseract_url = 'C:\\Program Files\\Tesseract-OCR\\tesseract.exe'
tesseract_url = 'C:\\Program Files\\Tesseract-OCR\\tesseract.exe'